### ISSUE TITLE
[FEATURE]: An option to specify table type

### ISSUE THREAD

**Issue by ndbs879827** [21Bruce/resolved-bot#29]
### Is there an existing issue for this feature?

- [x] I have searched for this issue

### Description of the problem

Right now there is no way to specify table type. If there are multiple table types for the same time on the same day, how will the system know which one to book? It would be great to be able to specify types like 'Indoors', 'Dining Room', 'Outdoors', 'Patio' etc. to make sure to get the right table.

### Planned Solution

N/A

### Alternatives

N/A

### Solution Specifics

N/A

**Comment by 21Bruce** [comment]
Implemented an interface to the api layer to include a preference for tables. Table preference is decided after each loop of time searches. So the structure is basically, given a priority list of times {T1 T2} and a priority list of table types {Ta1 Ta2}, the checking goes(rough pseudocode)

For slot in slots {
If slot.Time == T1 && slot.Type == Ta1 -> reserve
}

For slot in slots {
If slot.Time == T2 && slot.Type == Ta1 -> reserve
}

For slot in slots {
If slot.Time == T1 && slot.Type == Ta2 -> reserve
}

For slot in slots {
If slot.Time == T2 && slot.Type == Ta2 -> reserve
}

The changes involved modifying the resy api `reserve` operation, specifically the `find` step. We search the config of the slot for a field called `type`, which provides a string declaration of the type of table the slot corresponds to. See api/resy/doc.go for more info. 

We still need to implement the command line flag for adding tables, by @justin-s-wong already has a commit in progress for this, should be available sometime tomorrow.

**Comment by 21Bruce** [comment]
Ok, the command line parsing is done. I'd like some initial testing done for this. @ndbs879827 you can test these changes by cloning the branch `29-feature-an-option-to-specify-table-type`. Let us know if this is what you had in mind

**Comment by 21Bruce** [comment]
As an extra note, since these changes pass my initial testing, if you don't have any other concerns, this branch will get merged into develop in a day or so

**Comment by 21Bruce** [comment]
I've merged the changes into develop, but I'll keep the feature branch and this issue open for two days to anyone who would like to voice their opinion
